name = "whatsapp-cloudflare-workers-api-work"
main = "./Example/example.ts"
compatibility_date = "2025-02-24"
compatibility_flags = [ "nodejs_compat_v2" ]
logpush = true

[[kv_namespaces]]
binding = "KV_whatsappCloudflareWorkers"
id = "64b2f6c20a6146f386bede6ff9f8c21d"
